package pkg.mybatis.model;

public class Child {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CHILD.ID
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CHILD.FIRST_NAME
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CHILD.LAST_NAME
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CHILD.KINDERGARDEN_ID
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    private Integer kindergardenId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CHILD.ID
     *
     * @return the value of PUBLIC.CHILD.ID
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CHILD.ID
     *
     * @param id the value for PUBLIC.CHILD.ID
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CHILD.FIRST_NAME
     *
     * @return the value of PUBLIC.CHILD.FIRST_NAME
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CHILD.FIRST_NAME
     *
     * @param firstName the value for PUBLIC.CHILD.FIRST_NAME
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CHILD.LAST_NAME
     *
     * @return the value of PUBLIC.CHILD.LAST_NAME
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CHILD.LAST_NAME
     *
     * @param lastName the value for PUBLIC.CHILD.LAST_NAME
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CHILD.KINDERGARDEN_ID
     *
     * @return the value of PUBLIC.CHILD.KINDERGARDEN_ID
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    public Integer getKindergardenId() {
        return kindergardenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CHILD.KINDERGARDEN_ID
     *
     * @param kindergardenId the value for PUBLIC.CHILD.KINDERGARDEN_ID
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    public void setKindergardenId(Integer kindergardenId) {
        this.kindergardenId = kindergardenId;
    }
}