package pkg.mybatis.model;
import java.util.List;

public class Kindergarden {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.KINDERGARDEN.ID
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.KINDERGARDEN.KINDERGARDEN_NAME
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    private String kindergardenName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.KINDERGARDEN.COUNTRY
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    private String country;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.KINDERGARDEN.ID
     *
     * @return the value of PUBLIC.KINDERGARDEN.ID
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.KINDERGARDEN.ID
     *
     * @param id the value for PUBLIC.KINDERGARDEN.ID
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.KINDERGARDEN.KINDERGARDEN_NAME
     *
     * @return the value of PUBLIC.KINDERGARDEN.KINDERGARDEN_NAME
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    public String getKindergardenName() {
        return kindergardenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.KINDERGARDEN.KINDERGARDEN_NAME
     *
     * @param kindergardenName the value for PUBLIC.KINDERGARDEN.KINDERGARDEN_NAME
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    public void setKindergardenName(String kindergardenName) {
        this.kindergardenName = kindergardenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.KINDERGARDEN.COUNTRY
     *
     * @return the value of PUBLIC.KINDERGARDEN.COUNTRY
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.KINDERGARDEN.COUNTRY
     *
     * @param country the value for PUBLIC.KINDERGARDEN.COUNTRY
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    public void setCountry(String country) {
        this.country = country;
    }
}