package pkg.mybatis.dao;

import java.util.List;
import pkg.mybatis.model.Child;

public interface ChildMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CHILD
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CHILD
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    int insert(Child record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CHILD
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    Child selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CHILD
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    List<Child> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CHILD
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    int updateByPrimaryKey(Child record);
}