package pkg.mybatis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pkg.mybatis.model.ChildTeacher;

public interface ChildTeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CHILD_TEACHER
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    int deleteByPrimaryKey(@Param("childId") Integer childId, @Param("teacherId") Integer teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CHILD_TEACHER
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    int insert(ChildTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CHILD_TEACHER
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    List<ChildTeacher> selectAll();
}