package pkg.mybatis.dao;

import java.util.List;
import pkg.mybatis.model.Kindergarden;

public interface KindergardenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.KINDERGARDEN
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.KINDERGARDEN
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    int insert(Kindergarden record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.KINDERGARDEN
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    Kindergarden selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.KINDERGARDEN
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    List<Kindergarden> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.KINDERGARDEN
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    int updateByPrimaryKey(Kindergarden record);
}