package pkg.mybatis.dao;

import java.util.List;
import pkg.mybatis.model.Teacher;

public interface TeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEACHER
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEACHER
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEACHER
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    Teacher selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEACHER
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    List<Teacher> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEACHER
     *
     * @mbg.generated Tue May 22 11:48:09 EEST 2018
     */
    int updateByPrimaryKey(Teacher record);
}